#!/usr/bin/env bash
# Generate ansible/inventory.ini from `terraform output`.

set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
TF_DIR="$ROOT/terraform"
INVENTORY="$ROOT/ansible/inventory.ini"

if ! command -v terraform >/dev/null 2>&1; then
  echo "error: terraform not found on PATH" >&2
  exit 1
fi
if ! command -v jq >/dev/null 2>&1; then
  echo "error: jq not found on PATH (brew install jq)" >&2
  exit 1
fi

cd "$TF_DIR"

extract_ip() {
  jq -r --arg key "$1" '
    .[$key].value
    | if type == "array" then .[0] else . end
  '
}

OUTPUTS_JSON="$(terraform output -json)"
WORKER_IP="$(printf '%s' "$OUTPUTS_JSON" | extract_ip worker_ip)"
DB_IP="$(printf '%s' "$OUTPUTS_JSON" | extract_ip db_ip)"

if [[ -z "$WORKER_IP" || "$WORKER_IP" == "null" ]]; then
  echo "error: worker_ip is empty — did terraform apply succeed?" >&2
  exit 1
fi
if [[ -z "$DB_IP" || "$DB_IP" == "null" ]]; then
  echo "error: db_ip is empty — did terraform apply succeed?" >&2
  exit 1
fi

if command -v multipass >/dev/null 2>&1; then
  echo "Probing cloud-init on both VMs (60s budget per VM)..."
  for vm in "$(terraform output -raw worker_name 2>/dev/null || echo lab4-worker)" \
            "$(terraform output -raw db_name 2>/dev/null || echo lab4-db)"; do
    # Bounded poll — cloud-init may legitimately report status:error on
    # Multipass (harmless late-stage modules), but the VM is still usable.
    for _ in $(seq 1 30); do
      status="$(multipass exec "$vm" -- cloud-init status 2>/dev/null | awk -F': ' '/^status:/ {print $2}')"
      [[ "$status" == "done" || "$status" == "error" || "$status" == "disabled" ]] && break
      sleep 2
    done
    echo "  $vm: cloud-init=$status"
  done
fi

mkdir -p "$(dirname "$INVENTORY")"
cat > "$INVENTORY" <<EOF
# AUTO-GENERATED by scripts/gen-inventory.sh — do not edit by hand.
# Regenerate after every \`terraform apply\` / \`terraform destroy\`.

[workers]
worker ansible_host=$WORKER_IP

[db]
database ansible_host=$DB_IP

[all:vars]
ansible_user=ansible
ansible_python_interpreter=/usr/bin/python3
EOF

echo "wrote $INVENTORY"
echo "  workers: worker ($WORKER_IP)"
echo "  db:      db     ($DB_IP)"
